-- =====================================================================
-- Bronze Layer Data Profiling and Quality Assessment
-- =====================================================================

-- Set execution context
USE DATABASE SALES_DWH;
USE SCHEMA BRONZE;

-- Validate current context
SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();

-- =====================================================================
-- CUSTOMER DATA PROFILING
-- =====================================================================

-- Assess record completeness and null distribution across key columns
SELECT 
    COUNT(*) AS TOTAL_RECORDS,
    COUNT(CUSTOMERID) AS CUSTOMERID_NOT_NULL,
    COUNT(PERSONID) AS PERSONID_NOT_NULL,
    COUNT(STOREID) AS STOREID_NOT_NULL,
    COUNT(TERRITORYID) AS TERRITORYID_NOT_NULL,
    COUNT(DISTINCT ACCOUNTNUMBER) AS DISTINCT_ACCOUNTNUMBER,
    COUNT(DISTINCT ROWGUID) AS DISTINCT_ROWGUID,
    COUNT(MODIFIEDDATE) AS MODIFIEDDATE_NOT_NULL
FROM CUSTOMER_RAW;

-- Identify duplicate records based on primary/business key (CustomerID)
SELECT CUSTOMERID, COUNT(*) 
FROM CUSTOMER_RAW 
GROUP BY CUSTOMERID 
HAVING COUNT(*) > 1;

-- Identify duplicate account numbers (potential business key issue)
SELECT ACCOUNTNUMBER, COUNT(*)
FROM CUSTOMER_RAW 
GROUP BY ACCOUNTNUMBER
HAVING COUNT(*) > 1;

-- Classify customer type based on source system modeling
SELECT
    CASE
        WHEN PERSONID IS NOT NULL AND STOREID IS NULL THEN 'PERSON'
        WHEN PERSONID IS NULL AND STOREID IS NOT NULL THEN 'STORE'
        WHEN PERSONID IS NULL AND STOREID IS NULL THEN 'UNKNOWN'
        WHEN PERSONID IS NOT NULL AND STOREID IS NOT NULL THEN 'NOT_APPLICABLE'
    END AS CUSTOMER_TYPE,
    COUNT(*) AS RECORD_COUNT
FROM CUSTOMER_RAW
GROUP BY CUSTOMER_TYPE;

-- Validate temporal range of data
SELECT MIN(MODIFIEDDATE) AS MIN_MODIFIEDDATE,
       MAX(MODIFIEDDATE) AS MAX_MODIFIEDDATE
FROM CUSTOMER_RAW;

-- =====================================================================
-- PRODUCT DATA PROFILING
-- =====================================================================

-- Preview sample records
SELECT * FROM PRODUCT_RAW LIMIT 5;

-- Assess completeness for key numeric columns
SELECT 
    COUNT(*) AS TOTAL_RECORDS,
    COUNT(PRODUCTID) AS PRODUCTID_NOT_NULL,
    COUNT(SAFETYSTOCKLEVEL) AS SAFETYSTOCKLEVEL_NOT_NULL,
    COUNT(REORDERPOINT) AS REORDERPOINT_NOT_NULL,
    COUNT(DAYSTOMANUFACTURE) AS DAYSTOMANUFACTURE_NOT_NULL,
    COUNT(PRODUCTSUBCATEGORYID) AS PRODUCTSUBCATEGORYID_NOT_NULL,
    COUNT(PRODUCTMODELID) AS PRODUCTMODELID_NOT_NULL
FROM PRODUCT_RAW;

-- Validate StandardCost data quality (precision, negatives, zero values)
SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT(STANDARDCOST) AS NOT_NULL_COUNT,
    MIN(STANDARDCOST) AS MIN_VALUE,
    MAX(STANDARDCOST) AS MAX_VALUE,
    COUNT_IF(STANDARDCOST < 0) AS NEGATIVE_COUNT,
    COUNT_IF(STANDARDCOST = 0) AS ZERO_COUNT,
    COUNT_IF(STANDARDCOST != ROUND(STANDARDCOST,2)) AS INVALID_SCALE_COUNT
FROM PRODUCT_RAW;

-- Validate ListPrice data quality
SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT(LISTPRICE) AS NOT_NULL_COUNT,
    MIN(LISTPRICE) AS MIN_VALUE,
    MAX(LISTPRICE) AS MAX_VALUE,
    COUNT_IF(LISTPRICE < 0) AS NEGATIVE_COUNT,
    COUNT_IF(LISTPRICE = 0) AS ZERO_COUNT,
    COUNT_IF(LISTPRICE != ROUND(LISTPRICE,2)) AS INVALID_SCALE_COUNT
FROM PRODUCT_RAW;

-- Validate Weight data quality and identify missing values
SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT(WEIGHT) AS NOT_NULL_COUNT,
    MIN(WEIGHT) AS MIN_VALUE,
    MAX(WEIGHT) AS MAX_VALUE,
    COUNT_IF(WEIGHT < 0) AS NEGATIVE_COUNT,
    COUNT_IF(WEIGHT = 0) AS ZERO_COUNT,
    COUNT_IF(WEIGHT != ROUND(WEIGHT,2)) AS INVALID_SCALE_COUNT
FROM PRODUCT_RAW;

-- Identify records with missing weight
SELECT * 
FROM PRODUCT_RAW 
WHERE WEIGHT IS NULL;

-- Assess completeness of string-based attributes
SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT(NAME) AS NAME_NOT_NULL,
    COUNT(PRODUCTNUMBER) AS PRODUCTNUMBER_NOT_NULL,
    COUNT(COLOR) AS COLOR_NOT_NULL,
    COUNT(SIZE) AS SIZE_NOT_NULL,
    COUNT(SIZEUNITMEASURECODE) AS SIZE_UNIT_NOT_NULL,
    COUNT(WEIGHTUNITMEASURECODE) AS WEIGHT_UNIT_NOT_NULL,
    COUNT(PRODUCTLINE) AS PRODUCTLINE_NOT_NULL,
    COUNT(CLASS) AS CLASS_NOT_NULL,
    COUNT(STYLE) AS STYLE_NOT_NULL,
    COUNT(ROWGUID) AS ROWGUID_NOT_NULL
FROM PRODUCT_RAW;

-- Validate temporal consistency
SELECT MIN(MODIFIEDDATE), MAX(MODIFIEDDATE) 
FROM PRODUCT_RAW;

-- =====================================================================
-- SALES ORDER DETAIL DATA PROFILING
-- =====================================================================

-- Preview sample data
SELECT * FROM SALES_ORDER_DETAIL_RAW LIMIT 5;

-- Validate completeness and uniqueness
SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT(SALESORDERID) AS SALESORDERID_NOT_NULL,
    COUNT(SALESORDERDETAILID) AS SALESORDERDETAILID_NOT_NULL,
    COUNT(DISTINCT CARRIERTRACKINGNUMBER) AS DISTINCT_TRACKING_NUMBER,
    COUNT(ORDERQTY) AS ORDERQTY_NOT_NULL,
    COUNT(PRODUCTID) AS PRODUCTID_NOT_NULL,
    COUNT(SPECIALOFFERID) AS SPECIALOFFERID_NOT_NULL,
    COUNT(DISTINCT LOWER(ROWGUID)) AS DISTINCT_ROWGUID
FROM SALES_ORDER_DETAIL_RAW;

-- Validate UnitPrice metrics
SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT(UNITPRICE) AS NOT_NULL_COUNT,
    MIN(UNITPRICE) AS MIN_VALUE,
    MAX(UNITPRICE) AS MAX_VALUE,
    COUNT_IF(UNITPRICE < 0) AS NEGATIVE_COUNT,
    COUNT_IF(UNITPRICE = 0) AS ZERO_COUNT,
    COUNT_IF(UNITPRICE != ROUND(UNITPRICE,5)) AS INVALID_SCALE_COUNT
FROM SALES_ORDER_DETAIL_RAW;

-- Validate UnitPriceDiscount metrics
SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT(UNITPRICEDISCOUNT) AS NOT_NULL_COUNT,
    MIN(UNITPRICEDISCOUNT) AS MIN_VALUE,
    MAX(UNITPRICEDISCOUNT) AS MAX_VALUE,
    COUNT_IF(UNITPRICEDISCOUNT < 0) AS NEGATIVE_COUNT,
    COUNT_IF(UNITPRICEDISCOUNT = 0) AS ZERO_COUNT,
    COUNT_IF(UNITPRICEDISCOUNT != ROUND(UNITPRICEDISCOUNT,2)) AS INVALID_SCALE_COUNT
FROM SALES_ORDER_DETAIL_RAW;

-- Validate LineTotal consistency and precision
SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT(LINETOTAL) AS NOT_NULL_COUNT,
    MIN(LINETOTAL) AS MIN_VALUE,
    MAX(LINETOTAL) AS MAX_VALUE,
    COUNT_IF(LINETOTAL < 0) AS NEGATIVE_COUNT,
    COUNT_IF(LINETOTAL = 0) AS ZERO_COUNT,
    COUNT_IF(LINETOTAL != ROUND(LINETOTAL,6)) AS INVALID_SCALE_COUNT
FROM SALES_ORDER_DETAIL_RAW;

-- Validate business rule: LineTotal calculation
SELECT * 
FROM SALES_ORDER_DETAIL_RAW
WHERE LINETOTAL != ORDERQTY * UNITPRICE * (1 - UNITPRICEDISCOUNT);

-- Identify future-dated records (data anomaly)
SELECT COUNT(*) 
FROM SALES_ORDER_DETAIL_RAW
WHERE MODIFIEDDATE > CURRENT_TIMESTAMP();

-- Identify duplicate transactional records
SELECT SALESORDERID, SALESORDERDETAILID, COUNT(*)
FROM SALES_ORDER_DETAIL_RAW
GROUP BY SALESORDERID, SALESORDERDETAILID
HAVING COUNT(*) > 1;

-- Validate temporal range
SELECT MIN(MODIFIEDDATE), MAX(MODIFIEDDATE) 
FROM SALES_ORDER_DETAIL_RAW;

-- =====================================================================
-- SALES ORDER HEADER DATA PROFILING
-- =====================================================================

-- Preview data
SELECT * FROM SALES_ORDER_HEADER_RAW;

-- Validate completeness across key attributes
SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT(SALESORDERID) AS SALESORDERID_NOT_NULL,
    COUNT(REVISIONNUMBER) AS REVISIONNUMBER_NOT_NULL,
    COUNT(DISTINCT SALESORDERNUMBER) AS DISTINCT_ORDER_NUMBER,
    COUNT(STATUS) AS STATUS_NOT_NULL,
    COUNT(DISTINCT PURCHASEORDERNUMBER) AS DISTINCT_PO_NUMBER,
    COUNT(DISTINCT ACCOUNTNUMBER) AS DISTINCT_ACCOUNT_NUMBER,
    COUNT(CUSTOMERID) AS CUSTOMERID_NOT_NULL,
    COUNT(TERRITORYID) AS TERRITORYID_NOT_NULL,
    COUNT(BILLTOADDRESSID) AS BILLTOADDRESSID_NOT_NULL,
    COUNT(SHIPTOADDRESSID) AS SHIPTOADDRESSID_NOT_NULL,
    COUNT(SHIPMETHODID) AS SHIPMETHODID_NOT_NULL,
    COUNT(CREDITCARDID) AS CREDITCARDID_NOT_NULL,
    COUNT(CURRENCYRATEID) AS CURRENCYRATEID_NOT_NULL,
    COUNT(ONLINEORDERFLAG) AS ONLINEORDERFLAG_NOT_NULL,
    COUNT(DISTINCT CREDITCARDAPPROVALCODE) AS DISTINCT_APPROVAL_CODE,
    COUNT(DISTINCT COMMENT) AS DISTINCT_COMMENT,
    COUNT(DISTINCT ROWGUID) AS DISTINCT_ROWGUID
FROM SALES_ORDER_HEADER_RAW;

-- Validate monetary columns (SubTotal, TaxAmt, Freight, TotalDue)
SELECT
    COUNT(*),
    COUNT(SUBTOTAL),
    MIN(SUBTOTAL),
    MAX(SUBTOTAL),
    COUNT_IF(SUBTOTAL < 0),
    COUNT_IF(SUBTOTAL = 0),
    COUNT_IF(SUBTOTAL != ROUND(SUBTOTAL,4))
FROM SALES_ORDER_HEADER_RAW;

SELECT
    COUNT(*),
    COUNT(TAXAMT),
    MIN(TAXAMT),
    MAX(TAXAMT),
    COUNT_IF(TAXAMT < 0),
    COUNT_IF(TAXAMT = 0),
    COUNT_IF(TAXAMT != ROUND(TAXAMT,4))
FROM SALES_ORDER_HEADER_RAW;

SELECT
    COUNT(*),
    COUNT(FREIGHT),
    MIN(FREIGHT),
    MAX(FREIGHT),
    COUNT_IF(FREIGHT < 0),
    COUNT_IF(FREIGHT = 0),
    COUNT_IF(FREIGHT != ROUND(FREIGHT,4))
FROM SALES_ORDER_HEADER_RAW;

SELECT
    COUNT(*),
    COUNT(TOTALDUE),
    MIN(TOTALDUE),
    MAX(TOTALDUE),
    COUNT_IF(TOTALDUE < 0),
    COUNT_IF(TOTALDUE = 0),
    COUNT_IF(TOTALDUE != ROUND(TOTALDUE,6))
FROM SALES_ORDER_HEADER_RAW;

-- Validate temporal consistency
SELECT
    MIN(MODIFIEDDATE), MIN(ORDERDATE), MIN(DUEDATE), MIN(SHIPDATE),
    MAX(MODIFIEDDATE), MAX(ORDERDATE), MAX(DUEDATE), MAX(SHIPDATE)
FROM SALES_ORDER_HEADER_RAW;

-- Identify future-dated anomalies
SELECT COUNT(*) FROM SALES_ORDER_HEADER_RAW WHERE ORDERDATE > CURRENT_TIMESTAMP();
SELECT COUNT(*) FROM SALES_ORDER_HEADER_RAW WHERE DUEDATE > CURRENT_TIMESTAMP();
SELECT COUNT(*) FROM SALES_ORDER_HEADER_RAW WHERE MODIFIEDDATE > CURRENT_TIMESTAMP();

-- Identify duplicate orders
SELECT SALESORDERID, COUNT(*)
FROM SALES_ORDER_HEADER_RAW
GROUP BY SALESORDERID
HAVING COUNT(*) > 1;

-- Validate business rules: date relationships
SELECT *
FROM SALES_ORDER_HEADER_RAW 
WHERE DUEDATE < ORDERDATE OR SHIPDATE < ORDERDATE;

-- Validate categorical distributions
SELECT STATUS, COUNT(*) 
FROM SALES_ORDER_HEADER_RAW
GROUP BY STATUS
ORDER BY STATUS;

SELECT ONLINEORDERFLAG, COUNT(*)
FROM SALES_ORDER_HEADER_RAW
GROUP BY ONLINEORDERFLAG;

-- Validate financial consistency rule
SELECT *
FROM SALES_ORDER_HEADER_RAW
WHERE TOTALDUE != SUBTOTAL + TAXAMT + FREIGHT;